export const WEBSOCKET_CONNECT = "WEBSOCKET_CONNECT";
export const WEBSOCKET_SEND = "WEBSOCKET_SEND";
export const WEBSOCKET_DISCONNECT = "WEBSOCKET_DISCONNECT";
export const WEBSOCKET_OPEN = "WEBSOCKET_OPEN";
export const WEBSOCKET_CLOSE = "WEBSOCKET_CLOSE";
export const WEBSOCKET_MESSAGE = "WEBSOCKET_MESSAGE";
